[workspace]
resolver = "2"
members = [
    "ternvale-log",
    "ternvale-config",
    "ternvale-hv",
    "ternvale-acpi",
    "ternvale-vmm",
    "ternvale-devices",
    "ternvale-cli",
    "ternvale-agent-proto",
    "ternvale-agent",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false
